### ISSUE TITLE
nfc writing and partially reading wont work

### ISSUE THREAD

**Issue by Jona-Walpert** [Flipper-XFW/Xtreme-Firmware#504] opened 2024-01-01 11:38 UTC
### Problem Description

I encountered an issue with my Flipper Zero running the Xtreme Firmware, where I am unable to read or write NFC tags successfully. When attempting to read a new and empty tag, the device reports that only 133 out of 135 pages were read. However, I can successfully read all pages if the tags are unlocked using the password FF FF FF FF wich I found online. 

Additionally, when trying to write to an NFC tag, the device indicates that it is still locked, and there is an issue related to Auth 0 (refer to the attached picture).

### Steps to Reproduce

1. Attempt to read a new and empty NFC tag.
2. Observe the reported read result (133/135 pages).
3. Try reading the same tag after unlocking with the password FF FF FF FF.
4. Attempt to write to an NFC tag.
5. Observe the reported lock status and Auth 0 issue (as shown in the attached picture).

### Expected Behavior

The Flipper Zero with Xtreme Firmware should be able to read and write to NFC tags without encountering issues related to incomplete reads or authentication problems.

### Additional Information

- Flipper Zero model: [FZ.1]
- Xtreme Firmware version: [XFW-0052]
- Any relevant screenshots or error messages: [see picture]

![nfc-error](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/98217482/02e865ad-09ca-43f4-ba39-3eb4f7fc4711)

### Reproduction

1. Switch on
2. nfc
3. saved
4. select saved nfc file
5. write
6. error

### Logs

```Text
[useless qflipper logs]
```

### Anything else?

Logs always says succes. writing or readng all pages didnt work but logs show SUCCESS

**Comment by Jona-Walpert** [comment] 2024-01-01 11:39
![rad](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/98217482/a70507fa-642b-49bb-8f97-9c1bec6e927f)

**Comment by Sil333033** [comment] 2024-01-01 11:59
your card is locked by the lock bits. even with the passwords for all the pages you cant do anything. 
Those logs are useless btw, ignore them. They are referring to your actions via qflipper

**Comment by Jona-Walpert** [comment] 2024-01-01 16:45
> your card is locked by the lock bits. even with the passwords for all the pages you cant do anything. Those logs are useless btw, ignore them. They are referring to your actions via qflipper

Ok but I should be able to write it?

**Comment by Jona-Walpert** [comment] 2024-01-01 16:46
> words for all the pages you c

Because I still  cant write to a nfc tag... So the Issue is still present

**Comment by Willy-JL** [comment] 2024-01-01 17:02
explain how you are attempting to write to it.

**Comment by Jona-Walpert** [comment] 2024-01-01 17:05
I go to "NFC". then to "saved". Then I choose a saved nfc file. After that I click on "Write" and hold a nfc tag to the back of the flipper and Then the message apepars that you can see in the first picture

**Comment by Willy-JL** [comment] 2024-01-01 17:19
learning to use google might prove fruitful.
https://www.google.com/search?q=write+locked+ntag215+with+flipper+zer
https://www.reddit.com/r/flipperzero/comments/18e48gg/flipper_thinks_all_ntag215_cards_are_password/
https://github.com/flipperdevices/flipperzero-firmware/issues/3281
https://github.com/flipperdevices/flipperzero-firmware/pull/3285

the issue is resolved and merged into the firmware. it is already available in dev builds, and will be released in v53.

**Comment by Willy-JL** [comment] 2024-01-01 17:21
technically not resolved in a stable release however, so i will reopen and mark as pending release.

**Closed** 2024-02-02 10:18 UTC
Labels: bug, release-pending
